# This file used by make for docker-composer container operations
# including docker image build

version: '2.1'

services:
  app:
    image: ${APP_IMAGE}
    command:
      --listen=:8080 --path=/data
    labels:
      - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    build:
      context: .
