# This file used by make for docker-composer container operations
# including docker image build

version: '2.1'

services:
  app:
    image: ${APP_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var:/opt/app/var
      - ./html:/opt/app/html
    build:
      context: .
    networks:
       - app-network

networks:
  app-network:
    external:
      name: ${DCAPE_NET}
